---
- name: Malware Analysis Tools
  become: yes
  become_method: sudo
  apt: pkg="{{ item }}" state=latest
  with_items:
  - python-yara
  - python3-yara
  - yara
  - radare2
  - radare2-plugins
  - python-capstone
  - jclassinfo
  - pyew
  - gdb
  - gdb-arm-none-eabi
  - binutils-arm-none-eabi
  - andbug
  - classyshark
  - bytecode-viewer
  - dissy
  - gddrescue
  - okteta
#  - python-radare2
#  - radare2-vala
#  - radare2-java
